### ISSUE TITLE
请问能在R2S openwrt的Docker上运行吗？

### ISSUE THREAD

**Issue by super27035** [stilleshan/subconverter#1]
我试了在R2S上pull和部署，但不能成功运行，出现
stderr: standard_init_linux.go:211: exec user process caused "exec format error"
的警告，不知道如何解决，望指教！
<img width="651" alt="Screen Shot 2021-04-16 at 11 12 20 PM" src="https://user-images.githubusercontent.com/43180500/115046087-ad8aaa00-9f09-11eb-8358-d3b385827948.png">
<img width="1053" alt="Screen Shot 2021-04-16 at 11 11 30 PM" src="https://user-images.githubusercontent.com/43180500/115046101-b1b6c780-9f09-11eb-85f4-a329f3be3545.png">

**Comment by stilleshan** [comment]
不确定是不是架构问题,R2S是ARM的吧?

我这个是X86版本的.你尝试用官方的镜像应该是可以的  
[tindy2013/subconverter](https://hub.docker.com/r/tindy2013/subconverter)

我找时间研究下发布多版本的镜像...

**Comment by super27035** [comment]
感谢回复，我也想试试官方镜像，但由于也刚学习，运行
docker pull tindy2013/subconverter
之后，就不知道怎么部署了。要再研究一下，谢谢！

**Comment by super27035** [comment]
docker run -d -p 25500:25500 tindy2013/subconverter:latest

**Comment by stilleshan** [comment]
是这样的

**Comment by super27035** [comment]
我运行以上命令，好像是部署好了，也在运行，但好像进入本地访问 http://192.168.5.1:25500/ 得出 File not found.

**Comment by stilleshan** [comment]
已经成功了，具体怎么用你看下官方文档！

**Comment by super27035** [comment]
![Uploading Screen Shot 2021-04-16 at 11.12.20 PM.png…]()

**Comment by super27035** [comment]
<img width="1053" alt="Screen Shot 2021-04-16 at 11 11 30 PM" src="https://user-images.githubusercontent.com/43180500/115050079-f93f5280-9f0d-11eb-900a-e94b386a52d2.png">

**Comment by super27035** [comment]
好的，谢谢
