### ISSUE TITLE
返回502

### ISSUE THREAD

**Issue by viocha** [stilleshan/subconverter#10]
错误信息如下
Download profile(https://sub.ops.ci/sub?target=clash&new_name=true&url=https%3A%2F%2Fbulinkbulink.com%2Ffreefq%2Ffree%2Fmaster%2Fv2&insert=false&config=https%3A%2F%2Fraw.githubusercontent.com%2FACL4SSR%2FACL4SSR%2Fmaster%2FClash%2Fconfig%2FACL4SSR_Online_Full.ini&filename=%E6%B5%8B%E8%AF%95&emoji=true&list=false&tfo=false&scv=false&fdn=true&sort=false&udp=true&enable_filter=true&filter_script=function%20filter(node)%20%7B%0A%20%20%20%20if(node.EncryptMethod.includes('chacha20'))%0A%20%20%20%20%20%20%20%20return%20false%3B%0A%20%20%20%20return%20true%3B%0A%7D) failed with error: HTTP Response Status Code(502)

**Comment by stilleshan** [comment]
服务挂了，已重启。
