### ISSUE TITLE
现在已经可以成功使用你的这个arm64后端，请问有没有配套的subweb的arm版?

### ISSUE THREAD

**Issue by rzdbaba** [stilleshan/subconverter#3]
如题

**Comment by stilleshan** [comment]
我没有用 subweb,但是看了下项目的 Dockerfile 文件,是可以打包成 arm 镜像.

一会你关注下 https://github.com/stilleshan/dockerfiles 项目,我尝试打包一个你试试看.

**Comment by rzdbaba** [comment]
> 我没有用 subweb，但是看了下项目的 Dockerfile 文件，是可以打包成 arm 镜像.
> 
> 一会你关注下https://github.com/stilleshan/dockerfiles项目，我尝试打包一个你试试看.

好的  十分感谢

**Comment by stilleshan** [comment]
尝试了下报错了...你去官方项目提交 issue 看看吧.
