### ISSUE TITLE
Trojan ws

### ISSUE THREAD

**Issue by reizhi** [stilleshan/subconverter#4]
#https://github.com/tindy2013/subconverter/pull/411#issue-1071219561
原版在上月新增了 Trojan ws 兼容，这边似乎还没更新支持。

**Comment by stilleshan** [comment]
之前看官方一直有点bug.所以没更新.
明天发一版试试吧

**Comment by stilleshan** [comment]
镜像重新打包了

**Comment by reizhi** [comment]
感谢更新，不过发现原版似乎还有丢 host 参数的问题，只能等先解决了。
#https://github.com/tindy2013/subconverter/issues/431
