### ISSUE TITLE
Can you make /base a VOLUMN?

### ISSUE THREAD

**Issue by dzhuang** [stilleshan/subconverter#5]
So that we can override the files/snippets in it?

Thanks!

**Comment by stilleshan** [comment]
I don't know what's your mean exactly

Your can mount any files or folders in to the container with "-v" by yourself

**Comment by ifaintad** [comment]
Ok, I had thought that I should have a VOLUMN in Dockerfile before I can mount it. Thanks for the info.

**Comment by dzhuang** [comment]
Thanks!
