### ISSUE TITLE
groups和rulesets应该用toml

### ISSUE THREAD

**Issue by gtgc2005** [stilleshan/subconverter#6]
docker有bug

COPY groups.txt rulesets.txt /base/snippets/应该改成COPY groups.toml rulesets.toml /base/snippets/

toml的优先级最高，txt的配置并不会优先生效

**Comment by stilleshan** [comment]
感谢,已经修复,把默认 pref.yml 挂上了,里面默认是 txt.
之前自己测试每次都是挂了 pref
